### PR TITLE
tidying complete

### PR DESCRIPTION
**Pull request by matt-raines**
Atom Beautify ;)

### CODE REVIEW

**Comment by natalie-perret** [comment]
Hey Matt, your indenting looks great! My only suggestion would be to put paragraph <p> content on a different line and list <li> content on the same line. This best practice blog has some examples https://www.granneman.com/webdev/coding/formatting-and-indenting-your-html/

**Comment by natalie-perret** [comment]
hey matt, let me know if you're happy for me to merge this?

**Comment by matt-raines** [comment]
Happy as for you to merge @natalie-perret :)

**Comment by natalie-perret** [comment]
awesome stuff, thanks!

**Pull request merged**
